  conn_test (1).cpp
conn_test (1).obj : error LNK2019: _mysql_errno@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
conn_test (1).obj : error LNK2019: _mysql_error@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
conn_test (1).obj : error LNK2019: _mysql_init@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
conn_test (1).obj : error LNK2019: _mysql_real_connect@32_main 함수에서 참조되는 확인할 수 없는 외부 기호
conn_test (1).obj : error LNK2019: _mysql_select_db@8_main 함수에서 참조되는 확인할 수 없는 외부 기호
conn_test (1).obj : error LNK2019: _mysql_query@8_main 함수에서 참조되는 확인할 수 없는 외부 기호
conn_test (1).obj : error LNK2019: _mysql_store_result@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
conn_test (1).obj : error LNK2019: _mysql_fetch_row@4_main 함수에서 참조되는 확인할 수 없는 외부 기호
libmysql.lib : warning LNK4272: 'x64' 라이브러리 컴퓨터 종류가 'x86' 대상 컴퓨터 종류와 충돌합니다.
C:\Users\성원\source\repos\Project4\Debug\Project4.exe : fatal error LNK1120: 8개의 확인할 수 없는 외부 참조입니다.
